name: CI Builds

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux:
    name: Linux Builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2

      - name: Install dependencies
        run: |
          pnpm i

      - name: Build
        run: |
          pnpm build

      - name: Package
        run: |
          pnpm package

      - name: Collect artifacts
        run: |
          mv dist/quark-runtime-*.tar.bz2 quark-runtime.linux.tar.bz2

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Linux
          path: quark-runtime.linux.tar.bz2
